"""OpenAI-compatible API client with vision model support."""

import base64
import logging
import time
from pathlib import Path

from openai import OpenAI
from PIL import Image

logger = logging.getLogger(__name__)


def encode_image_base64(image_path: Path) -> str:
    """Encode an image to base64.

    Args:
        image_path: Path to the image.

    Returns:
        The base64 encoded image with data URI prefix.
    """
    with open(image_path, "rb") as f:
        image_data = base64.b64encode(f.read()).decode("utf-8")
    
    # Determine mime type
    suffix = image_path.suffix.lower()
    mime_types = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp",
        ".gif": "image/gif",
    }
    mime_type = mime_types.get(suffix, "image/jpeg")
    
    return f"data:{mime_type};base64,{image_data}"


def describe_image(
    image_path: Path,
    model: str,
    system_prompt: str,
    temperature: float = 0.7,
    max_tokens: int = 8192,
    base_url: str | None = None,
    api_key: str | None = None,
) -> str:
    """Generate a description of an image via OpenAI-compatible API.

    Args:
        image_path: Path to the image to describe.
        model: Name of the model to use (e.g., 'gpt-4o', 'gpt-4-vision-preview').
        system_prompt: System prompt to guide the description.
        temperature: Temperature for generation.
        max_tokens: Maximum tokens in response.
        base_url: API base URL (e.g., 'https://api.openai.com/v1', 'https://openrouter.ai/api/v1').
        api_key: API key for authentication.

    Returns:
        The description generated by the model.

    Raises:
        openai.OpenAIError: On API error.
    """
    if not api_key:
        raise ValueError("API key is required for OpenAI-compatible provider")
    
    logger.debug(f"Encoding image: {image_path.name}")
    encode_start = time.time()

    # Get image dimensions for logging
    with Image.open(image_path) as img:
        width, height = img.size

    image_data_uri = encode_image_base64(image_path)
    encode_time = time.time() - encode_start
    logger.debug(
        f"Image encoded in {encode_time:.2f}s - "
        f"size: {width}x{height}"
    )

    base_url_info = base_url or "default (https://api.openai.com/v1)"
    logger.debug(f"Creating OpenAI client (base_url: {base_url_info})")
    
    client = OpenAI(
        api_key=api_key,
        base_url=base_url,
    )

    logger.info(f"Sending request to OpenAI-compatible API, model '{model}' for: {image_path.name}")
    api_start = time.time()

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": system_prompt,
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "Describe this image.",
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": image_data_uri,
                        },
                    },
                ],
            }
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )

    api_time = time.time() - api_start
    response_content = response.choices[0].message.content or ""
    logger.info(f"Response received in {api_time:.2f}s (length: {len(response_content)} chars)")
    logger.debug(f"Response preview: {response_content[:100]}...")

    return response_content


def list_models(base_url: str | None = None, api_key: str | None = None) -> list[str]:
    """List available models from OpenAI-compatible API.

    Args:
        base_url: API base URL.
        api_key: API key for authentication.

    Returns:
        List of model IDs that support vision.

    Raises:
        openai.OpenAIError: On API error.
    """
    if not api_key:
        raise ValueError("API key is required to list models")
    
    client = OpenAI(
        api_key=api_key,
        base_url=base_url,
    )
    
    logger.debug(f"Fetching models from {base_url or 'default OpenAI endpoint'}")
    models = client.models.list()
    
    # Filter for vision-capable models
    # Common patterns: gpt-4-vision, gpt-4o, gpt-4-turbo (has vision), claude-3, etc.
    vision_keywords = ["vision", "gpt-4o", "gpt-4-turbo", "claude-3", "gemini", "llava", "qwen"]
    
    vision_models = []
    for model in models.data:
        model_id = model.id.lower()
        # Check if any vision keyword is in the model ID
        if any(keyword in model_id for keyword in vision_keywords):
            vision_models.append(model.id)
    
    # If no vision models found, return all models (some APIs don't follow naming conventions)
    if not vision_models:
        logger.warning("No vision models detected by keyword, returning all models")
        vision_models = [model.id for model in models.data]
    
    logger.info(f"Found {len(vision_models)} vision-capable models")
    return sorted(vision_models)


def test_connection(base_url: str | None = None, api_key: str | None = None) -> tuple[bool, str]:
    """Test connection to OpenAI-compatible API.

    Args:
        base_url: API base URL.
        api_key: API key for authentication.

    Returns:
        Tuple of (success, message).
    """
    if not api_key:
        return False, "API key is required"
    
    try:
        client = OpenAI(
            api_key=api_key,
            base_url=base_url,
        )
        
        # Try to list models as a connection test
        models = client.models.list()
        model_count = len(list(models.data))
        
        return True, f"✓ Connected successfully! Found {model_count} models."
    
    except Exception as e:
        error_msg = str(e)
        logger.error(f"Connection test failed: {error_msg}")
        return False, f"✗ Connection failed: {error_msg}"
