"""Unified vision client that routes to appropriate provider."""

import logging
from pathlib import Path

from . import ollama_client, openai_client

logger = logging.getLogger(__name__)


def describe_image(
    image_path: Path,
    model: str,
    system_prompt: str,
    provider: str = "ollama",
    temperature: float = 0.7,
    # Ollama-specific
    num_ctx: int = 8192,
    ollama_host: str | None = None,
    # OpenAI-compatible specific
    max_tokens: int = 8192,
    openai_base_url: str | None = None,
    openai_api_key: str | None = None,
) -> str:
    """Generate a description of an image using the specified provider.

    Args:
        image_path: Path to the image to describe.
        model: Name of the model to use.
        system_prompt: System prompt to guide the description.
        provider: Provider to use ('ollama' or 'openai').
        temperature: Temperature for generation.
        num_ctx: Context window size (Ollama only).
        ollama_host: Ollama server URL (Ollama only).
        max_tokens: Maximum tokens in response (OpenAI only).
        openai_base_url: OpenAI-compatible API base URL.
        openai_api_key: OpenAI-compatible API key.

    Returns:
        The description generated by the model.

    Raises:
        ValueError: If provider is unknown or required parameters are missing.
        Exception: Provider-specific exceptions.
    """
    if provider == "ollama":
        logger.debug("Using Ollama provider")
        return ollama_client.describe_image(
            image_path=image_path,
            model=model,
            system_prompt=system_prompt,
            temperature=temperature,
            num_ctx=num_ctx,
            ollama_host=ollama_host,
        )
    
    elif provider == "openai":
        logger.debug("Using OpenAI-compatible provider")
        return openai_client.describe_image(
            image_path=image_path,
            model=model,
            system_prompt=system_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            base_url=openai_base_url,
            api_key=openai_api_key,
        )
    
    else:
        raise ValueError(f"Unknown provider: {provider}. Must be 'ollama' or 'openai'.")


def list_models(
    provider: str = "ollama",
    ollama_host: str | None = None,
    openai_base_url: str | None = None,
    openai_api_key: str | None = None,
) -> list[str]:
    """List available models from the specified provider.

    Args:
        provider: Provider to use ('ollama' or 'openai').
        ollama_host: Ollama server URL (Ollama only).
        openai_base_url: OpenAI-compatible API base URL.
        openai_api_key: OpenAI-compatible API key.

    Returns:
        List of model IDs.

    Raises:
        ValueError: If provider is unknown or required parameters are missing.
    """
    if provider == "ollama":
        from .config import get_ollama_models
        return get_ollama_models(ollama_host)
    
    elif provider == "openai":
        return openai_client.list_models(
            base_url=openai_base_url,
            api_key=openai_api_key,
        )
    
    else:
        raise ValueError(f"Unknown provider: {provider}. Must be 'ollama' or 'openai'.")


def test_connection(
    provider: str = "ollama",
    ollama_host: str | None = None,
    openai_base_url: str | None = None,
    openai_api_key: str | None = None,
) -> tuple[bool, str]:
    """Test connection to the specified provider.

    Args:
        provider: Provider to use ('ollama' or 'openai').
        ollama_host: Ollama server URL (Ollama only).
        openai_base_url: OpenAI-compatible API base URL.
        openai_api_key: OpenAI-compatible API key.

    Returns:
        Tuple of (success, message).
    """
    if provider == "ollama":
        from .config import test_ollama_connection
        return test_ollama_connection(ollama_host)
    
    elif provider == "openai":
        return openai_client.test_connection(
            base_url=openai_base_url,
            api_key=openai_api_key,
        )
    
    else:
        return False, f"Unknown provider: {provider}"
